name: CD
on: 
    push:
        branches:
            - main
jobs:
    First-CD:
        runs-on: ubuntu-latest
        steps:
            - name: Get the repository code
              uses: actions/checkout@v4
            - name: Cache deps # кэширование зависимостей
              uses: actions/cache@v4
              with: 
                  path: ~/.npm
                  key: node-modules-${{hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              run: npm ci
            - name: Test application
              run: npm run test
        

