name: Deploy React App

on: 
    push: 
        branches:
            - main
            paths-ignore: # es pathov ignora anum u ete
                            # daje push anenq meka joby chi miana
                - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying