name: Print Pull Request Context
on:  #github actions WF triggers
  workflow_dispatch:
  pull_request:
        types: [ opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ toJSON(github) }}"